// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX6I8xDwidgtetm81Zm7yOIbbS3eoIJwY',
    appId: '1:556902198748:web:3b24fcbba2348b5bf9b319',
    messagingSenderId: '556902198748',
    projectId: 'clofou-training-app',
    authDomain: 'clofou-training-app.firebaseapp.com',
    storageBucket: 'clofou-training-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAteUSvnjHfUrmYLNtZnGXhvPDiBI-YZAo',
    appId: '1:556902198748:android:f6b80d8f1cfbd094f9b319',
    messagingSenderId: '556902198748',
    projectId: 'clofou-training-app',
    storageBucket: 'clofou-training-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6yF7vio6wXn8nufUJcPpxeV07hVOnkb0',
    appId: '1:556902198748:ios:3558d64c08f3f7ebf9b319',
    messagingSenderId: '556902198748',
    projectId: 'clofou-training-app',
    storageBucket: 'clofou-training-app.appspot.com',
    iosClientId: '556902198748-tjqh42c8eq6fue8j6sa74hkq0lec2e91.apps.googleusercontent.com',
    iosBundleId: 'com.example.trainingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6yF7vio6wXn8nufUJcPpxeV07hVOnkb0',
    appId: '1:556902198748:ios:3558d64c08f3f7ebf9b319',
    messagingSenderId: '556902198748',
    projectId: 'clofou-training-app',
    storageBucket: 'clofou-training-app.appspot.com',
    iosClientId: '556902198748-tjqh42c8eq6fue8j6sa74hkq0lec2e91.apps.googleusercontent.com',
    iosBundleId: 'com.example.trainingApp',
  );
}
